### ISSUE TITLE
HDR Tone Remapping control?

### ISSUE THREAD

**Issue by Mibix** [J3n50m4t/Home-Assistant-DreamScreen-Service#40]
I guess this is more of a question/feature request but is there a way to turn on and off the HDR Tone Remapping from Kodi?  Can't figure out how to do it if it is possible.

**Comment by zanix** [comment]
Use the `dreamscreen.set_hdr_tone_remapping` service

![image](https://user-images.githubusercontent.com/1580378/115088566-ac3b8c00-9ecd-11eb-828f-9a507d2c0444.png)

Or here is a script example
```yaml
script:
  dreamscreen_hdr_off:
    alias: "DreamScreen - Turn off HDR Tone Mapping"
    sequence:
      - service: dreamscreen.set_hdr_tone_remapping
        data:
          entity_id: dreamscreen.living_room
          remapping: 0
  dreamscreen_hdr_on:
    alias: "DreamScreen - Turn on HDR Tone Mapping"
    sequence:
      - service: dreamscreen.set_hdr_tone_remapping
        data:
          entity_id: dreamscreen.living_room
          remapping: 1
```
